# Generated by Django 5.2.9 on 2025-12-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lanchonete', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='lanche',
        ),
    ]
