# Generated by Django 5.2.9 on 2025-12-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lanchonete', '0002_remove_pedido_lanche'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
